bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash: dircolors: command not found
Traceback (most recent call last):
  File "/home/opencal/opencal/OpenCAL/main.py", line 2, in <module>
    from hardware.hardware_controller import HardwareController
  File "/home/opencal/opencal/OpenCAL/hardware/__init__.py", line 1, in <module>
    from .hardware_controller import HardwareController
  File "/home/opencal/opencal/OpenCAL/hardware/hardware_controller.py", line 1, in <module>
    from .camera_controller import CameraController
  File "/home/opencal/opencal/OpenCAL/hardware/camera_controller.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
steps=1000)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opencal/opencal/.venv/lib/python3.11/site-packages/gpiozero/devices.py", line 108, in __call__
    self = super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opencal/opencal/.venv/lib/python3.11/site-packages/gpiozero/input_devices.py", line 1147, in __init__
    a=InputDevice(a, pull_up=True, pin_factory=pin_factory),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opencal/opencal/.venv/lib/python3.11/site-packages/gpiozero/devices.py", line 108, in __call__
    self = super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opencal/opencal/.venv/lib/python3.11/site-packages/gpiozero/input_devices.py", line 79, in __init__
    super().__init__(pin, pin_factory=pin_factory)
  File "/home/opencal/opencal/.venv/lib/python3.11/site-packages/gpiozero/devices.py", line 552, in __init__
    self.pin_factory.reserve_pins(self, pin)
  File "/home/opencal/opencal/.venv/lib/python3.11/site-packages/gpiozero/pins/__init__.py", line 88, in reserve_pins
    raise GPIOPinInUse(
gpiozero.exc.GPIOPinInUse: pin GPIO5 is already in use by <gpiozero.InputDevice object on pin GPIO5, pull_up=True, is_active=False>
 |
  File "/home/opencal/opencal/.venv/lib/python3.11/site-packages/smbus2/smbus2.py", line 416, in write_byte
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
